# displaying attribute

In [1]:
import pandas as pd
Fire = pd.read_csv("Data\Fire_Data\\viirs-jpss1_2024_Portugal.csv")
Fire.head(0)

Empty DataFrame
Columns: [latitude, longitude, bright_ti4, scan, track, acq_date, acq_time, satellite, instrument, confidence, version, bright_ti5, frp, daynight, type]
Index: []

# checking Missing values

In [2]:
Fire.isna().sum()

latitude      0
longitude     0
bright_ti4    0
scan          0
track         0
acq_date      0
acq_time      0
satellite     0
instrument    0
confidence    0
version       0
bright_ti5    0
frp           0
daynight      0
type          0
dtype: int64

# Keeping Fires with high and normal confidence

In [3]:
low = Fire.shape
Fire = Fire[ Fire["confidence"].str.lower() != "l" ].copy()
print(F"Dropped {low[0]-Fire.shape[0]} Fire with low confidence ")

Dropped 396 Fire with low confidence

# Keeping only Vegetation Fire

In [4]:
all = Fire.shape
Fire = Fire[Fire["type"] == 0].copy()
print(F"Dropped {all[0]-Fire.shape[0]} Fire that are'nt presumed vegetation fire ")

Dropped 243 Fire that are'nt presumed vegetation fire

# keeping Fire data from continental Portugal

In [ ]:
out = Fire.shape

Fire = Fire[
    (Fire['longitude'] > -9.55) & 
    (Fire['latitude'] > 36.9) & 
    (Fire['latitude'] < 42.2)
]

print(F"Dropped {out[0]-Fire.shape[0]} Fire that are'nt located in continental Portugal ")

Dropped 386 Fire that are'nt located in continental Portugal

In [8]:
cols_to_keep = ['longitude','latitude']
Fire = Fire [cols_to_keep].copy()
Fire

       longitude  latitude
0       -7.50605  41.40449
1       -7.41553  38.01472
2       -7.41353  38.00985
3       -7.41025  38.01191
4       -7.41392  38.01099
...          ...       ...
12005   -7.93598  38.28211
12006   -7.35872  39.10413
12007   -7.67712  38.12000
12008   -8.56459  41.67453
12009   -7.51337  40.02723

[10985 rows x 2 columns]

In [9]:
Fire.to_csv("Data\Fire_Data\\filtered_fire_data.csv", index=False)